[project]
name = "agenticai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kristina Pavlovska", email = "141680987+pavlovskakristina@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "google-genai==1.12.1",
    "openai==2.44.0",
    "python-dotenv==1.1.0",
]

[project.scripts]
agenticai = "agenticai:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
